# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Antoine COUPAT
# Description of the Site
description: IT Engineer - 3D / VR / Web
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio, IT, 3D, VR, Web
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/pexels-sun-8674521.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: thedevslot@gmail.com
linkedin_username: antoinecoupat
github_username:  ACoupat

# Google Analytics
#google-analytics: UA-163806439-1

# Name of the Author
author-name: Antoine COUPAT
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: <strong>Welcome to my website!</strong><br/><br/> My name is Antoine, and I am passionate about computer science in many aspects, especially <strong>3D and immersive technologies</strong>.<br/><br/>My engineering degree in computer science and my various professional experiences have allowed me to build a generalist profile with an accent on <strong>3D imaging, Virtual Reality (VR)</strong> and <strong>web technologies</strong>. Naturally curious and open-minded, I like to stay close to source code and technical subjects as much as being involved in <strong>project management and customer relationships</strong>.
author-about-fr: Passioné d'informatique sous de nombreux aspects, je m'intéresse particulièrement la 3D et aux technologies immersives et possède un certain bagage technique et scientifique en matière de technologies web. J'éprouve également de l'intérêt pour l'UI et l'UX Design sont pour moi des sujets incontournables de nos jours. Ma formation d'ingénieur en informatique et mes différentes expériences professionnelles dans le milieu m'ont permis de me forger un profil généraliste, allant du développement au suivi de projet, en passant par la relation client et la conception logicielle.
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"
permalink: "projects/:slug"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections: 
  projects :
    output: true  
  positions :
    output: true  